name: CI/CD Pipeline

on:
    push:
        branches: ["main"]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository}}

jobs:
    test-security-build:
        runs-on: ubuntu-latest

        services:
            mongo:
                image: mongo:6.0
                ports:
                    - 27017:27017
                options: >-
                    --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:

            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up Go
              uses: actions/setup-go@v5

            - name: Cache Go modules
              uses: actions/cache@v4
              with:
                path: |
                  ~/go/pkg/mod
                  ~/.cache/go-build
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum')}}
                restorse-keys: |
                  ${{ runner.os }}-go-

            - name: Install dependencies
              run: go mod tidy

            