name: CI/CD Pipeline

on:
    push:
        branches: ["main"]

permissions:
    contents: read
    security-events: write

jobs:
    test-security-build:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: 1.24

            - name: Cache Go modules
              uses: actions/cache@v4
              with:
                path: |
                  ~/go/pkg/mod
                  ~/.cache/go-build
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum')}}
                restore-keys: |
                  ${{ runner.os }}-go-

            - name: Install dependencies
              run: go mod tidy

            - name: Run golangci-lint for static code analysis
              uses: golangci/golangci-lint-action@v8
              with:
                version: latest
                args: --timeout=5m

            - name: Run Gosec Security Scanner
              uses: securego/gosec@master
              with:
                args: '-no-fail -fmt sarif -out results.sarif ./...'

            - name: Upload Gosec SARIF file
              uses: github/codeql-action/upload-sarif@v3
              with:
                sarif_file: results.sarif

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build Docker image
              run: |
                docker build -t ${{ vars.DOCKERHUB_USERNAME }}/jwt-auth-server:${{ github.sha }} \
                        -t ${{ vars.DOCKERHUB_USERNAME }}/jwt-auth-server:latest .

            - name: Run Trivy vuln scanner
              id: trivy
              uses: aquasecurity/trivy-action@0.28.0
              with:
                image-ref: ${{ vars.DOCKERHUB_USERNAME }}/jwt-auth-server:${{ github.sha }}
                format: sarif
                output: trivy-results.sarif
                severity: HIGH,CRITICAL
                ignore-unfixed: true
                vuln-type: os,library
              continue-on-error: true

            - name: Upload Trivy SARIF file
              uses: github/codeql-action/upload-sarif@v3
              with:
                sarif_file: trivy-results.sarif

            - name: Fail if vuln found
              if: steps.trivy.outcome == 'failure'
              run: exit 1

            - name: Push Docker image
              run: |
                docker push ${{ vars.DOCKERHUB_USERNAME }}/jwt-auth-server:${{ github.sha }}
                docker push ${{ vars.DOCKERHUB_USERNAME }}/jwt-auth-server:latest